### ISSUE TITLE
test

### ISSUE THREAD

**Issue by xswqaz** [xswqaz/atprog#1]
https://github.com/hrydgard/ppsspp/issues/7993#issuecomment-143441842

```
virt-v2v: This guest has virtio drivers installed.
virt-v2v: warning: this guest has Windows Group Policy Objects (GPO) and a
new virtio block device driver was installed.  In some circumstances, Group
Policy may prevent new drivers from working (resulting in a 7B boot error).
 If this happens, try disabling Group Policy before doing the conversion.
virt-v2v: warning: this guest has Anti-Virus (AV) software and a new virtio
block device driver was installed.  In some circumstances, AV may prevent
new drivers from working (resulting in a 7B boot error).  If this happens,
try disabling AV before doing the conversion.
```

**Comment by xswqaz** [comment]
| aaa | bbb |
| --- | --- |
| ccc | ddd |

**Comment by xswqaz** [comment]
```
2015-11-26 17:43:55.983 3781 WARNING nova.scheduler.utils [req-5450a862-d783-4c62-8984-784bf00d7856 ed97d1c097224ca78703cac8c89ec2a8 0deef6478eb24e008253a00a30c1f8aa - - -] Failed to compute_task_build_instances: No valid host was found. There are not enough hosts available.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 142, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 84, in select_destinations
    filter_properties)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 90, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.

2015-11-26 17:43:55.984 3781 WARNING nova.scheduler.utils [req-5450a862-d783-4c62-8984-784bf00d7856 ed97d1c097224ca78703cac8c89ec2a8 0deef6478eb24e008253a00a30c1f8aa - - -] [instance: abbb97c0-8ace-4eab-9781-6fb142ec0384] Setting instance to ERROR state.
```
